# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6c97cc2a5220a68b0a000016e778c60aa2addfba4b160545ab97055d058631cecef8d1d886e508f1e3858815a7f650eeaf0d3a77513aa40238c96c95099e689d

test:
  secret_key_base: e8966c2aa701ae77cf3f7baed0c92a0b2891c4db9091e7a9c65c3d7f9c211db8ff06ac8f8783a9fe07c2c228e33677ac58e93d4bdf78a809180266849ab6f285

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
